export const GET_PARTNER_REQUEST = 'GET_PARTNER_REQUEST';
export const GET_PARTNER_SUCCESS = 'GET_PARTNER_SUCESS';
export const GET_PARTNER_FAILURE = 'GET_PARTNER_FAILURE';

export const POST_ADMIN_LOGIN_REQUEST = 'POST_ADMIN_LOGIN_REQUEST';
export const POST_ADMIN_LOGIN_SUCCESS = 'POST_ADMIN_LOGIN_SUCESS';
export const POST_ADMIN_LOGIN_FAILURE = 'POST_ADMIN_LOGIN_FAILURE';